services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL
      - BETTER_AUTH_SECRET
      - BETTER_AUTH_URL
      - HCA_CLIENT_ID
      - HCA_CLIENT_SECRET
      - HACKATIME_CLIENT_ID
      - HACKATIME_CLIENT_SECRET
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET
      - AIRTABLE_API_KEY
      - AIRTABLE_BASE_ID
      - AIRTABLE_RSVP_TABLE_NAME
      - REQUIRE_BASICAUTH
      - BASICAUTH_USERNAME
      - BASICAUTH_PASSWORD
      - HACKCLUB_CDN_TOKEN
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
