version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL
      - BETTER_AUTH_SECRET
      - BETTER_AUTH_URL
      - HCA_CLIENT_ID
      - HCA_CLIENT_SECRET
      - HACKATIME_CLIENT_ID
      - HACKATIME_CLIENT_SECRET
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET
      - AIRTABLE_API_KEY
      - AIRTABLE_BASE_ID
      - AIRTABLE_RSVP_TABLE_NAME
      - REQUIRE_BASICAUTH
      - BASICAUTH_USERNAME
      - BASICAUTH_PASSWORD
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
