import { NextRequest, NextResponse } from "next/server"
import prisma from "@/lib/prisma"
import { auth } from "@/lib/auth"
import { headers } from "next/headers"
import { getUserRoles, hasRole, Role } from "@/lib/permissions"

function formatDate(date: Date): string {
  const month = date.getMonth() + 1
  const day = date.getDate()
  const year = date.getFullYear()
  let hour = date.getHours()
  const ampm = hour >= 12 ? "PM" : "AM"
  hour = hour % 12 || 12
  return `${month}/${day}/${year} ${hour} ${ampm}`
}

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const session = await auth.api.getSession({ headers: await headers() })
  if (!session) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  }

  const { id: projectId } = await params

  const project = await prisma.project.findUnique({
    where: { id: projectId },
    select: { userId: true, title: true },
  })

  if (!project) {
    return NextResponse.json({ error: "Project not found" }, { status: 404 })
  }

  const roles = await getUserRoles(session.user.id)
  const isAdmin = hasRole(roles, Role.ADMIN)

  if (project.userId !== session.user.id && !isAdmin) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 })
  }

  const workSessions = await prisma.workSession.findMany({
    where: { projectId },
    include: { media: true },
    orderBy: { createdAt: "desc" },
  })

  const entries = workSessions.map((ws) => {
    const dateStr = formatDate(ws.createdAt)
    const images = ws.media
      .filter((m) => m.type === "IMAGE")
      .map((m) => `![image](${m.url})`)
      .join("\n")

    const parts = [
      `# ${dateStr} - ${ws.title}`,
      "",
      `_Time spent: ${ws.hoursClaimed}h_`,
      "",
      ws.content,
    ]

    if (images) {
      parts.push("", images)
    }

    return parts.join("\n")
  })

  const markdown = [
    "<!--",
    "  This journal is auto generated by Stasis.",
    "-->",
    "",
    entries.join("\n\n"),
    "",
  ].join("\n")

  return new NextResponse(markdown, {
    headers: {
      "Content-Type": "text/markdown",
      "Content-Disposition": `attachment; filename="JOURNAL.md"`,
    },
  })
}
